// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjM3tAdFGfPhlDxuhFzuSx3m4NJxrRk0M',
    appId: '1:172978851082:web:1a5b29b48497255d3f7ef3',
    messagingSenderId: '172978851082',
    projectId: 'lepoteau-80eb8',
    authDomain: 'lepoteau-80eb8.firebaseapp.com',
    databaseURL: 'https://lepoteau-80eb8.firebaseio.com',
    storageBucket: 'lepoteau-80eb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAv3RMUVB5dn8zwm70AGgXsp8Bzs4KSm8',
    appId: '1:172978851082:android:0ad5fd2cd6e3c3913f7ef3',
    messagingSenderId: '172978851082',
    projectId: 'lepoteau-80eb8',
    databaseURL: 'https://lepoteau-80eb8.firebaseio.com',
    storageBucket: 'lepoteau-80eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tgniw0vZKPD_MEG2-qP9JX8_qeuE_tc',
    appId: '1:172978851082:ios:610f78b001190fde3f7ef3',
    messagingSenderId: '172978851082',
    projectId: 'lepoteau-80eb8',
    databaseURL: 'https://lepoteau-80eb8.firebaseio.com',
    storageBucket: 'lepoteau-80eb8.appspot.com',
    iosBundleId: 'com.example.videohub',
  );
}
